### ISSUE TITLE
Backup problem with azcopy (azure uploadprovider)

### ISSUE THREAD

**Issue by daneb255** [bitnami/bitnami-docker-azure-cli#1]
**Description**

Cannot create backup with the latest influxdb helm chart (2.2.6) and azure-upload-provider.

**Steps to reproduce the issue:**

1. Create fresh aks cluster
2. add latest bitnami helm chart
3. create helm chart with 

```
helm upgrade --install influx bitnami/influxdb --namespace VAR --set "backup.enabled=true" --set "backup.cronjob.schedule=0 2 * * *" --set "backup.uploadProviders.azure.existingSecret=azure-key" --set "backup.uploadProviders.azure.containerName=backup_container" --set "backup.uploadProviders.azure.enabled=true" --set "auth.existingSecret=influx-secret" --set "auth.admin.username=user"
```

**Describe the results you received:**

azure-cli logs ->
```
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
ERROR: Connection error while attempting to download azcopy 10.8.0. You could also install the specified azcopy version to /bin manually. ([Errno 1] Operation not permitted: '/bin')
```

**Describe the results you expected:**

Success upload message :)

**Comment by alvneiayu** [comment]
hi @daneb255 

Let me try to reproduce the issue and I will come back with some information.

Thanks a lot

Álvari

**Comment by alvneiayu** [comment]
Hi @daneb255 

I am not expert in this container. Doing some investigation, I saw that azcopy is not present inside the container. Did you install it in your own image? Another thing is our containers are running by default with the user 1001, maybe this limitation can produce you also permission problems.

Thanks a lot

Álvaro

**Comment by daneb255** [comment]
Hey @alvneiayu ,

no I haven´t tried my own image. But yeah it could be, that you need to chmod the binaries for the USER 1001, before the USER is set. Is az-copy actually included in the azure-cli package?
https://github.com/bitnami/bitnami-docker-azure-cli/blob/f27c1f4b15aec0b859ad8c975a9a8a341d197ca7/2/debian-10/Dockerfile#L27

Greetings
Daniel

**Comment by alvneiayu** [comment]
hi @daneb255 

I did a test calling the command  and it seems that it is not included by default. I think that you need to include it modifying the Dockerfile to use it.

Thanks a lot and sorry for the late reply

Álvaro

**Comment by daneb255** [comment]
Hey @alvneiayu ,

but I guess everyone has this problem with the docker image for backing up influx. Maybe we could fix it in the repo?
Thank you very much!
Greetings
Daniel

**Comment by alvneiayu** [comment]
hi @daneb255 

Well, let me open an internal task to talk with my team. So, I created an internal task to investigate and decide the best option and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot for your time

Álvaro

**Comment by daneb255** [comment]
Hey @alvneiayu ,
is there any news regarding this issue? :)
Thanks!
Greetings
Daniel

**Comment by alvneiayu** [comment]
hi @daneb255 

The issue is still in our backlog, I can not provide you an ETA. We are still working on it.

Thanks

Álvaro

**Comment by daneb255** [comment]
Hey @alvneiayu , thanks for the information. I created my own image but not able to set up pullsecrets for the backup image. (Created an issue here -> https://github.com/bitnami/charts/issues/6856)

So I downloaded the helm chart and edit some values in the upload-azure.sh script ->

az config set extension.use_dynamic_install=yes_without_prompt
az storage azcopy blob sync --source {{ .Values.backup.directory }} --container {{ .Values.backup.uploadProviders.azure.containerName }}

and also added imagePullSecrets in cronjob-backup.yaml (but it´s not important for this repo here)

But now I´m able to create an influxdb backup

**Comment by alvneiayu** [comment]
hi @daneb255

Thanks for sharing your solution. This is something that we can take it into account if finally the azcopy is included inside the azure-cli docker image. The issue is still in backlog.

Again, thanks a lot

Álvaro

**Comment by daneb255** [comment]
Hey @alvneiayu ,

with my fix you don´t need to implement azcopy as an single application. azcopy is also an extension in az (az config set extension.use_dynamic_install=yes_without_prompt) :)

Greetings
Daniel

**Comment by alvneiayu** [comment]
hi @daneb255 

wow, thanks a lot for sharing your solution. It will be really helpful for the community and also for me, I am not expert in this container. So using this, we don't need to include azcopy as you said. I am going to close the internal issue because if we can use azcopy enabling the az extensions, in my opinion this is a corner case.

Thanks a lot

Álvaro

**Comment by daneb255** [comment]
You're welcome :)

**Comment by alvneiayu** [comment]
hi @daneb255

I closed the internal task. If I can help you with something else.

Thanks a lot

Álvaro
