### ISSUE TITLE
az storage blob sync command fails with lack of permission to install azcopy

### ISSUE THREAD

**Issue by jcalvarado1965** [bitnami/bitnami-docker-azure-cli#2]
### Name and Version

bitnami/azure-cli:2.33.1

### What steps will reproduce the bug?

1. Run a shell in the container
2. Export AZURE_STORAGE_CONNECTION_STRING to a valid container connection string 
3. Run the command 
`az storage blob sync --source <some-folder> --container <container-name>`

### What is the expected behavior?

Should sync the folder contents to the container without error

### What do you see instead?

```
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Connection error while attempting to download azcopy 10.13.0. You could also install the specified azcopy version to /bin manually. ([Errno 1] Operation not permitted: '/bin')
```

### Additional information

The az command is trying to download azcopy to /bin folder, which fails as the default user (1001) does not have permission. One solution might be to include azcopy in the image /bin folder (must be a matching version)

**Comment by rafariossaa** [comment]
Hi,
  Could you try running the container as root ? That way the `/bin/` folder should be accessible.

**Comment by jcalvarado1965** [comment]
> Hi, Could you try running the container as root ? That way the `/bin/` folder should be accessible.

Yes this is a workaround. Of course it has security downside which is why I brought up the issue. The solution could be just installing azcopy in the container (https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy) assuming that this version of azcopy is the same that az is looking for. If that assumption breaks then the problem is hard to solve.

**Comment by rafariossaa** [comment]
I am creating an internal task to look for a solution for this.
Maybe you don't need to run it as root, just launch it and execute `docker exec -u root` to get into the container and run the command. Once you have it installed, you don't need to run it as root, even you could create your own image with the command you have just  installed.

**Comment by jcalvarado1965** [comment]
Thanks for the update. FYI this is in the context of fixing an issue with the bitnami Helm charts for InfluxDB (https://github.com/bitnami/charts/tree/master/bitnami/influxdb, specifically the backup to Azure feature) so creating a separate image is not a good option. I'm not sure how to use the approach you describe with Kubernetes. There is initContainers but that can only be used with mounted volumes I think.

**Comment by rafariossaa** [comment]
The idea is that you create you own image and then use it where you need it, but it is true you will need to update it when there is a new release from Bitnami.
